spring:
  application:
    name: service-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    data-username: root
    data-password: 123456
    url: jdbc://mysql:localhost:3306/shop?serverTimezone=Asia/shanghai&useUnicode=true&characterEncoding=utf-8
server:
  port: 8300
