#server:
#  port: 8200
#spring:
#  application:
#    name: service-gateway
#
#logging:
#  level:
#    root: info
#  pattern:
#    console:  '[%-5level] %clr(%d{HH:mm:ss}){cyan} %logger - %clr(%msg){green} [%clr(%thread{20}){cyan}]%n'